### ISSUE TITLE
People: Some faces are not visible in overview

### ISSUE THREAD

**Issue by monnypython** [photoprism/photoprism#1576]
I'm not sure if this is a bug.

So far I got the face clusters displayed and was able to name the different people. I currently have 100 people registered. I recently got no more clusters displayed. in the info bubble at the bottom I get the number of new people displayed.
Doesn't that mean I should see 34 clusters?

![2021-09-30_21-18](https://user-images.githubusercontent.com/42573701/135517143-bee8cd39-c357-4cc9-ab51-aaacb8c28fcc.png)

I also have the problem that I get a lot of pictures in "face: new" on which all people were named.

---

Edit:
This is what i get when click on Persons / New:

    2021-10-01 12:08:31 DEBU http: GET /api/v1/faces? 
    count=120&offset=0&q=&all=&order=relevance&markers=true&unknown=true (200) [88.042087ms]

    2021-10-01 12:08:31 WARN marker: face ZSJ3EQGSUGCKNIJTJOTKHOJPMNKDEB73 not found

    2021-10-01 12:08:31 WARN marker: face ZS3U23PABZNVIUE36UBXKP7EG4JI2M7J not found

    2021-10-01 12:08:31 WARN marker: face ZNA6EMI2KPKLYSEJHBRXMOEWZSIE5IO7 not found

    2021-10-01 12:08:31 WARN marker: face YFKCEBPN5TFIMEWM7QHY5FSX5USMJUCH not found

    2021-10-01 12:08:31 WARN marker: face WYSY3VBWZJRXNEUHPT5VFVW22AJKHUOQ not found

    2021-10-01 12:08:31 WARN marker: face UNWIKCCVGXTMBZWQNEDHULBPTUNCGIGO not found

    2021-10-01 12:08:31 WARN marker: face TMMOSCKVYYRXBA3KZPRAJJCA5GP2ZCGF not found

    2021-10-01 12:08:31 WARN marker: face TAEE7CJZZK74VIJ4RHWRME2C7JHET575 not found

    2021-10-01 12:08:31 WARN marker: face SO5UZV7A5VCBRBOTJVAMJUIPNYPKSBPV not found

    2021-10-01 12:08:31 WARN marker: face PN4AJQ522TWKUL3NQKK7ZTCWO6VOYTRB not found

    2021-10-01 12:08:31 WARN marker: face OSMWB5YPILVZEGW7N6CQI3X6XOCFS74R not found

    2021-10-01 12:08:31 WARN marker: face OLRNXUV3KRKLQ3XSZVJTSKSZ425VZ2WM not found

    2021-10-01 12:08:31 WARN marker: face NKZI2D2BYOR6KICMIEMIW3ZXFHOB4T4M not found

    2021-10-01 12:08:31 WARN marker: face MOE6FMHIBSDUWNEHB7IWGPZHCX32BTEK not found

    2021-10-01 12:08:31 WARN marker: face LNIXL77SWZCT4PX5VRUKWI2ZF5RZ5CGC not found

    2021-10-01 12:08:31 WARN marker: face KH7MTBCNO7U46CTTUUBEMMA4DT7CG4WA not found

    2021-10-01 12:08:31 WARN marker: face K3CIGIS4D7JWTDUDYOJAOESFK3BDJ3FB not found

    2021-10-01 12:08:31 WARN marker: face JXKR4UMP6RNI7DHPIWMZBCFRDXGJ3QWV not found

    2021-10-01 12:08:31 WARN marker: face JX3Z2QOTGKW4W2ON7R362VZ7T6UDKFJN not found

    2021-10-01 12:08:31 WARN marker: face IT63FYACJYKYBVD5R3KI6XZ5OER6S6BU not found

    2021-10-01 12:08:31 WARN marker: face HFDVX7VDKVQZE5HU2MJ3ADY53VL6APCM not found

    2021-10-01 12:08:31 WARN marker: face FFUCW5QYLOYQK673CBHVQHRJRDNPTYDB not found

    2021-10-01 12:08:31 WARN marker: face DO7UNYNUF2Z7C5CUSFUHXKN5S4CINPGY not found

    2021-10-01 12:08:31 WARN marker: face CYMWHCYSCM52TMU7URQQTP55Y7VVSNHR not found

    2021-10-01 12:08:31 WARN marker: face CCOBM6B5SKAVMBYKUZT3T6ZL36W25NA2 not found

    2021-10-01 12:08:31 WARN marker: face BNKS25Z6XF4VHT32MDFWEICZAZO65ATP not found

    2021-10-01 12:08:31 WARN marker: face AI42ORPUXPNBQNEYPXAMZ3SN6NQMEWV2 not found

    2021-10-01 12:08:30 WARN marker: face AG6TI5FPERKAVV4HHBPTZNWRZKD4236J not found

    2021-10-01 12:08:30 WARN marker: face 7NHCOFBDUE27BZGMW4LJGFJUCZJARS3P not found

    2021-10-01 12:08:30 WARN marker: face 67HMXS3S57GPD7TMJZW6APCXJ6EAMO5L not found

    2021-10-01 12:08:30 WARN marker: face 562SO7L657IBYW3FFSQACSRWIVC5P42Z not found

    2021-10-01 12:08:27 DEBU http: GET /api/v1/subjects? 
    count=480&offset=0&q=&all=&order=relevance&files=1&type=person (200) [17.39571ms]

    ....

**Comment by lastzero** [comment]
Does this still happen with our latest version? Looks like there are face clusters without a (valid) matching marker, which usually doesn't happen. Maybe because you marked all of them as invalid? @graciousgrey Can you test this?

**Comment by graciousgrey** [comment]
@monnypython I could reproduce it. A normal index should fix this.

**Comment by monnypython** [comment]
@lastzero The bug still occurred in the version from September 25th. After the update to the current stable, I get "no people found" matching the display of the cluster.

@graciousgrey At this point, re-indexing hadn't helped either. I had done this a couple of times.

---

I cannot understand the following behavior of the face recognition:
- no persons are displayed in the "NEW" tab
- But if I go to "SHOW ALL NEW FACES" and assign a name to a "new" face (this is a person who already exists in my collection but could not yet be automatically assigned), the existing person will have several pictures assigned from the area "face: new"
- Doesn't that mean that these images should have been displayed as a cluster?

In "face: new" there are still several hundred or thousand pictures. No new clusters have been generated since the problem in my first post. Not even after several "... face index".

**Comment by lastzero** [comment]
@monnypython Please use our latest update from October :)

A new person shows up in the new people tab when there are at least 4 similar faces, so that they form a cluster. A single unknown face is not a cluster, unless you set `PHOTOPRISM_FACE_CLUSTER_CORE: 1` in your configuration: https://docs.photoprism.org/getting-started/config-options/

**Comment by lastzero** [comment]
When you manually label an unknown face, you can simply compare it to other faces. The software otherwise first needs to cluster faces into similar groups to see a pattern, which your human brain does faster and better. You can however play with the config variables to enforce more aggressive clustering, e.g. try reducing the cluster core to 2, reset all faces and re-index them.

**Comment by lastzero** [comment]
Started a new Development Preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview
