### ISSUE TITLE
[Exif]: "Date/Time Original"/"Create Date" parsed incorrectly

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#219]
Indexing did not get exif's "Date/Time Original" or "Create Date" right for some of my photos. `exiftool` seems to be able to parse everything correctly on all photos. As a result, the photo appears to be taken in 2020, as (I guess) indexing falls back to the file's `mtime`

I'd be willing to provide you with a sample by some other means (than this GH issue). Any suggestions?

**Comment by lastzero** [comment]
hello@photoprism.org either as link or attachment if files are not too big

**Comment by lastzero** [comment]
Make sure to use our latest build so that you can see date / time details in the edit dialog. Last build had an issue with the time zone there, but it's fixed now.

**Comment by lastzero** [comment]
Thank you for testing! ❤️

**Comment by linosgian** [comment]
I pulled develop and the issue persists. I've sent you the sample through mail

**Comment by lastzero** [comment]
Received! Thought you're using our pre-built Docker image, but makes sense you have a dev environment...

**Comment by lastzero** [comment]
No error messages or warnings in the log?

**Comment by linosgian** [comment]
Oh damn, I forgot to include those in my original description. Yes, all of the photos that get the wrong date throw the following:
`ERRO[2020-01-24T14:50:34Z] ascii not terminated with nul as expected`

**Comment by lastzero** [comment]
@linosgian May I forward your test file to @dsoprea? Hope he can help with this.

**Comment by dsoprea** [comment]
It sounds like the timestamp couldn't even be recovered from the file, much less parsed. Can you share what the raw strings from the file should be and what PP is showing?

There are nul-terminated and non-oil terminated strings in EXIF. Each tag specifies this in the standard. I previously had forgiveness for this when not correct but switched to be more strict in the big refactor that just happened.

If you can actually give me the timestamps and one or more files that experienced this (you said there were many examples), then I can look into it.

**Comment by lastzero** [comment]
This JPEG file should "work": https://dl.photoprism.org/fixtures/testdata/import/QSYC4981.JPG

**Comment by lastzero** [comment]
@linosgian Is it possible that you received the "broken" file via WhatsApp?

**Comment by dsoprea** [comment]
This is well tested against JPEGs. I'm assuming his are nonconforming, though may turn out to be a common case. At this point, we just need to reproduce.

**Comment by lastzero** [comment]
@dsoprea Can you test with the JPEG file I provided? Could be a WhatsApp bug or something...

**Comment by linosgian** [comment]
@lastzero you can share it. I don't recall whether I downloaded it from Whatsapp, but it could be, since all of the problematic images are very low quality JPG. OTOH `exiftool` seems to be parsing it correctly.

**Comment by dsoprea** [comment]
Good to go. Looks like the code I added the strictness to was general string-handling code, which leads me to believe that this is going to have a very large impact. I reverted it to the previous state and confirmed that it worked with v1, broke with v2, and worked after the fix.

**Comment by lastzero** [comment]
Master build is running (takes ~30 minutes): https://travis-ci.org/photoprism/photoprism/builds/641978947

Also updated our docs and test files along the way.

@linosgian When the new image is pushed to Docker hub (or you build from develop), you can test again and are free to close this issue :)

**Comment by linosgian** [comment]
I've tested this with the latest build and now all the photos seem to be parsed correctly. I think we can close this one.

:tada:
