### ISSUE TITLE
Add new album fails with error 409 "already exists" 

### ISSUE THREAD

**Issue by Mandarancio** [photoprism/photoprism#2929]
Hi, 

I am running the last release of Photoprism using the docker image on my Unraid server using `Mariadb` as database. 
However I am running into a problem, every time I try to create a new album (both from the albums section or directly from a selections of pictures) I get the error that the album does exists already (of course is not the case).
On the log I got the following message: 

```
time="2022-11-21T14:20:07+01:00" level=debug msg="api: abort /api/v1/albums with code 409 ('November 2022' already exists)"
```

Could it be a db problem? Or something else?

Thank you very much in advance!
Martino

**Comment by lastzero** [comment]
This problem existed in case the album was deleted (which means it is currently hidden). However, we should have fixed this issue. Can you please check the exact build number at the bottom of the Settings page?

**Comment by Mandarancio** [comment]
Hi @lastzero ,  I checked and the album was not deleted, the build number is the follow: 220527-005770ca
Could it be some mysql schema problem?

**Comment by lastzero** [comment]
No, you simply need to update.

**Comment by lastzero** [comment]
Was fixed here: https://docs.photoprism.app/release-notes/#june-17-2022

👉 https://docs.photoprism.app/getting-started/updates/

**Comment by Mandarancio** [comment]
HI I updated the docker image to the build `221118-e58fee0fb`, however I am still not able to create new album, now I get the error:
```
time="2022-11-22T19:49:53+01:00" level=error msg="album: Error 1364: Field 'id' doesn't have a default value (create)"
time="2022-11-22T19:49:53+01:00" level=debug msg="api-v1: abort /api/v1/albums with code 500 (unexpected error, please try again)"
```
So I think is a problem with the mysql schema...

**Comment by Mandarancio** [comment]
I fixed it by changing the database schema adding the `auto_increment` flag to the album id

**Comment by lastzero** [comment]
No one else has reported this... Maybe you migrated from SQLite or an unsupported MariaDB/MySQL version? I can really only guess at this point, which is probably not very helpful.
