### ISSUE TITLE
UX: Restoring the scroll state on back navigation is broken

### ISSUE THREAD

**Issue by AlynxZhou** [photoprism/photoprism#5211]
#### 1. What is not working as documented?

In web browser, if I scroll down some steps (as the page will load more when scrolled to bottom, you have to make it load) and open a folder in folders view, then click back to return to folders view, it will try to restore to previous position, but it won't automatically load more folders when reaching bottom, so the position is not correct. You always stop at initial loaded folders, which makes it hard to use if you are trying finding some old photos, you have to manually scroll to trigger auto loading to reach previous position.

#### 2. How can we reproduce it?

1. Go to 'folders' view
2. Scroll down to bottom to trigger auto loading more folders
3. Click a folder that is loaded with auto loading, not a initial loaded folder
4. Click back button of browser
5. It will try to restore previous scroll position, but it won't trigger auto loading when reaches bottom, so it always stops at initial loaded folders.

#### 3. What behavior do you expect?

It saves previously loaded folders and restore to the position correctly, or while restoring the position it automatically triggers reloading and restore the position correctly. 

#### 4. What could be the cause of your problem?

I can see it did 1 auto loading when reached to bottom on restoring position, but then it stops to restoring position, maybe we need some way to continue loading and scrolling until reaches the correct position.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 250707-d28b3101e-Linux-x86_64

(b) Database Type & Version: mariadb from 12.0.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

(c) Operating System Types & Versions: Arch Linux 6.16.4-arch1-1

(d) Browser Types & Versions: Both Firefox and Chrome on macOS can reproduce this.

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? This can be reproduced in Private window.

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Ryzen 3 PRO 5350G

(b) Physical Memory & Swap Space in GB: 32GB/32GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...: 4-HDD RAID10

(d) Anything else that might be helpful to know? None

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No, I reproduced this in my home and I directly connected to PhotoPrism's HTTP port.

**Comment by graciousgrey** [comment]
Thanks for the report and the clear reproduction hints!

**What’s happening**
– The scroll position is remembered and a restore is triggered when you navigate back.
– However, the restore callback currently fires only once right after mount. At that moment, the album/folder item near the bottom often isn’t in the DOM yet because the list is still loading in batches (infinite scroll). As a result, the browser can’t scroll to a target that hasn’t been rendered, so you end up at the top again.

**Why this is expected with our current loading strategy**
– Albums and Folders views use progressive loading with virtualization / placeholders to keep memory and rendering costs under control. See [Developer Guide](https://docs.photoprism.app/developer-guide/ui/infinite-scrolling/)
– On back-navigation we do restore, but we don’t retry once more items arrive, so the first (and only) attempt can miss when the target item is far down the list.

**Two ways forward (trade-offs)**
1) “Wait longer” approach
   – Delay the single restore callback in hopes that enough items have loaded.
   – Doesn’t reliably fix slow connections or very large lists; still races.

2) “Load enough & retry” approach (recommended)
   – Persist both the last clicked item’s UID and its index (position) when navigating into an item.
   – On return:
     a) Increase the initial batch so the saved index is included, e.g. request count = max(default, savedIndex + smallBuffer).
     b) Re-attempt restore whenever a batch finishes until either:
        • the saved index is loaded (then scroll to the item/approximate offset), or
        • a sane cap is reached.
   – Because our API supports count/offset, we can request a larger first page or jump via offset when needed
   – With pseudo-virtualization in place, fetching metadata models for N items is cheap; thumbs render only when visible.

**Implementation sketch**
– Persist on click:
 ` history.state = { uid, index, scrollY }`
– On the Albums/Folders page 
  • Read saved { uid, index } on mounted.
  • Compute` initialCount = Math.max(defaultCount, index + buffer)`.
  • Trigger first load with initialCount (or offset/index-aware query).
  • After each “batch appended” event, call tryRestore():
```
if (!restored && loadedCount > index) {
        // Option A: precise
        scrollToElementByUid(uid);
        restored = true;
      } else if (!restored && indexKnown) {
        // Option B: approximate early jump; refine once the target renders
        container.scrollTop = estimatedTileHeight * index;
      }
```
  • Stop retrying once restored or a hard limit is reached.

**Notes / limits**
– “Load all” in one go is risky (time/memory) on very large libraries; better to load “enough” based on index plus a small buffer, then retry restore as batches arrive.
– We should also reset any accumulated back-navigation offset after a successful restore (see #2627) to avoid growing first-load sizes across sessions.

If there are no objections, we’ll proceed with option (2): save UID+index on navigation, increase the initial batch size based on index, and retry scrolling after each appended batch until the target exists. This should make back-navigation deterministic even when the destination is far down the list and the connection is slow.

**Links for context**
- [Infinite Scrolling](https://docs.photoprism.app/developer-guide/ui/infinite-scrolling/)
- [Search API (count/offset)](https://docs.photoprism.app/developer-guide/api/search/)
- #2597
-  #2627
-  #896

**Comment by lastzero** [comment]
@AlynxZhou These changes should resolve the issue. Let us know if it works!

I'll start a new preview build soon so you can test it:
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by AlynxZhou** [comment]
I've built the latest commit today, it still does not return to previous position when backing to all folders page.

**Comment by lastzero** [comment]
I tested it again, and it worked for me. How did you build it? Does it work with our prebuilt `:preview` Docker image? Have you tried different browsers? Did you clear the browser cache? What were the exact steps?

**Comment by AlynxZhou** [comment]
> I tested it again, and it worked for me. How did you build it? Does it work with our prebuilt `:preview` Docker image? Have you tried different browsers? Did you clear the browser cache? What were the exact steps?

I didn't use docker, instead I built it from source with latest commit. It may because I didn't clear the browser cache, let me have a try. I just tested with Firefox.

**Comment by AlynxZhou** [comment]
I tried again with both Chrome and Firefox with cache cleared, it is still not work for me.

**Comment by AlynxZhou** [comment]
I am building it with following PKGBUILD, I modify it to use the revision that contains your commit:

```
# Maintainer:  shtrophic <aur@shtrophic.net>
# Contributor: Evine Deng <evinedeng@hotmail.com>
# Contributor: Thomas Eizinger <thomas@eizinger.io>

_pkgname=photoprism
pkgname=photoprism-alynx
pkgver=251004
_commit=d7ee54e
_pkgver="${pkgver}-${_commit}"
pkgrel=1
pkgdesc="AI-Powered Photos App for the Decentralized Web"
arch=('x86_64' 'aarch64')
url="https://github.com/${_pkgname}/${_pkgname}"
license=('AGPL-3.0-or-later')
depends=(glibc glib2 libvips tensorflow)
makedepends=(git go npm findutils)
optdepends=("darktable: for RAW to JPEG conversion"
            "ffmpeg: for video transcoding and thumbnail extraction"
            "libva: for video transcoding"
            "imagemagick: for image conversion"
            "libheif: for HEIC/HEIF image conversion"
            "mariadb: for MySQL database driver"
            "perl-image-exiftool: for extracting metadata"
            "rawtherapee: for RAW to JPEG conversion")
source=("git+https://github.com/photoprism/photoprism.git#commit=${_commit}"
        "https://dl.${_pkgname}.app/tensorflow/facenet.zip"
        "https://dl.${_pkgname}.app/tensorflow/nasnet.zip"
        "https://dl.${_pkgname}.app/tensorflow/nsfw.zip"
        "${_pkgname}-import.service"
        "${_pkgname}-import.timer"
        "${_pkgname}.service"
        "${_pkgname}.sysusers"
        "${_pkgname}.tmpfiles"
        "${_pkgname}.user.service"
        "defaults.yml")
backup=("etc/${_pkgname}/defaults.yml")
provides=("photoprism")
conflicts=("photoprism" 'photoprism-facenet' 'photoprism-nasnet' 'photoprism-nsfw')
replaces=('photoprism-facenet' 'photoprism-nasnet' 'photoprism-nsfw')
b2sums=('SKIP'
        'ae3fe8162773ca9c84be2ea49dbc33e8a381d25cbbb51660c9f7a0764b89128eb8b40aceb10272e2579f277f76b8622d1f366e38e7c290266280c1db268365c5'
        '846cc4ce2d8c170c6442cf1f3a235d49744ff704300b619947bd425861ac4312d5465c749fd1179e4c25163d3a3428cd31359b7ea1521fa6edab81dba88074a0'
        'ca264c8ba2f999490c1335767286ddfe42a92d8606c371f17b5aa3f333bda3ade9c4f2451f7df7489946c9ae503f82351879a9876cd80e036a7991945e1242ec'
        'f5a06fd26f15afa7b71bd66afba800488fad697567754b6efc0d20f55955c043ba817d280b1d80c901ccbfcf085f11ad289624946bcd4bf2c3f3ee963a431c2d'
        'e75033ee265dddf39cb4f0d1cfc1e86a540da37c9787e3c13040b6fc039437d6684be3b59d63f001864f98f46afd49847b86b4fc6bedf891be87881a4bb83cf0'
        '3896b95ddda233270591e673f564bb3c7c537f9140d9ad0451259249d0bd956daf2b2cc70c3ba7fbd2971e97e126e13ecde368388c8e160708fbccad206c5d55'
        '02a752c8dda9c1611cac8119cf603bb8147dda1aa68fabaa9be61952e1839132d190691a68a01d0443d3750f76319a9e77e7fb9f175d5dbd0f527e5e4529ede8'
        'f8ad9373b97b6f5bda10caa193ae3f6700f8e15d82f30a2c8ad0fec02c5c25c3ad1f62ae524aa5e28b07312016d31c2918a3a9a3b172e61128fe054b129eecbe'
        '96d8d89499adfd1e3fba1b729133f3a01dbe16b2cb11deacc7e0e69620530c8f28e19911b16368816d98ce8e4ffa9645e8cb0429c82314179c335e736db87198'
        '8f5589b39c579d91151c528fec7e94c651ebf00776e5b84ada18ea0dc5ea4a64e13fb4af7bab3fc9493480a53541e36c6c4ebfe81f14c1e0f189f8fe8b561088')

prepare() {
    export GOPATH="$srcdir/go"
    export GOFLAGS="-modcacherw -mod=readonly"

    cd "$_pkgname"
    go mod download
    npm --prefix=frontend install --cache "$srcdir/npm-cache"
}

build() {
    export CGO_CFLAGS="$CFLAGS -I/usr/include/tensorflow"
    export CGO_CPPFLAGS="$CPPFLAGS"
    export CGO_CXXFLAGS="$CXXFLAGS"
    export NODE_ENV=production
    export GOPATH="$srcdir/go"

    cd "$_pkgname"
    local buildid="$_pkgver-$(uname -s)-$(uname -m)"
    local ldflags="
	-s -w \
	-linkmode external \
	-extldflags '$LDFLAGS' \
	-X main.version=$buildid
    "
    go build \
	-trimpath \
	-buildmode=pie \
	-mod=readonly \
	-modcacherw \
	-ldflags "$ldflags" \
	-o "$_pkgname" \
	"./cmd/$_pkgname/$_pkgname.go"

    npm --prefix=frontend run build
}

package() {
    find {facenet,nasnet,nsfw} -type f -exec install -Dm644 {} "$pkgdir/usr/share/$_pkgname/"{} \;

    install -Dm644 "$_pkgname-import".* 	     -t "$pkgdir/usr/lib/systemd/system"
    install -Dm644 "$_pkgname.service"      	"$pkgdir/usr/lib/systemd/system/$_pkgname.service"
    install -Dm644 "$_pkgname.sysusers"     	"$pkgdir/usr/lib/sysusers.d/$_pkgname.conf"
    install -Dm644 "$_pkgname.tmpfiles"     	"$pkgdir/usr/lib/tmpfiles.d/$_pkgname.conf"
    install -Dm644 "$_pkgname.user.service" 	"$pkgdir/usr/lib/systemd/user/$_pkgname.service"
    install -Dm644 "defaults.yml"            	"$pkgdir/etc/$_pkgname/defaults.yml"

    cd "$_pkgname"
    install -Dm755 "$_pkgname"              	"$pkgdir/usr/bin/$_pkgname"
    install -Dm644 LICENSE		     -t "$pkgdir/usr/share/licenses/$_pkgname"

    cd assets
    find {locales,profiles,static,templates} -type f -exec install -Dm644 {} "$pkgdir/usr/share/$_pkgname/"{} \;
}
```

**Comment by graciousgrey** [comment]
@lastzero I can confirm that it does not seem work when scrolling far down in e.g. the folders view. It does work when not scrolling to far.

**Comment by lastzero** [comment]
@AlynxZhou Since you are building from source, I recommend testing a higher `idleDelay` value:

https://github.com/photoprism/photoprism/blob/316cd2c919b889cdd0db87174558f0d408ee0008/frontend/src/common/notify.js#L70

It could be that it works for me locally, but not for your library, which may be slower or not hosted locally — in which case, the delay would be too short. Since I can't test it the way you can, it would help a lot if you could test this and report back.

**Comment by lastzero** [comment]
@AlynxZhou Please test again with this change, which increases the request batch size from 60 to 180 items.

**Comment by lastzero** [comment]
If this doesn't help and you're willing to experiment so we can improve it further, here are some additional variables to adjust the behavior:

https://github.com/photoprism/photoprism/blob/1117e0b1dcf29c6544966e633df3738e35ecafea/frontend/src/common/view.js#L692-L695

**Comment by AlynxZhou** [comment]
> [@AlynxZhou](https://github.com/AlynxZhou) Please test again with this change, which increases the request batch size from 60 to 180 items.

I tried with this change, it still does not help. It loads once, and stops to scroll down further.

**Comment by AlynxZhou** [comment]
I changed idleDelay to `const idleDelay = 144;`, still not helps. It loads once, and does not scroll down.

**Comment by lastzero** [comment]
Did you change it in [photoprism/frontend/src/common/notify.js](https://github.com/photoprism/photoprism/blob/316cd2c919b889cdd0db87174558f0d408ee0008/frontend/src/common/notify.js#L70)? Otherwise, it may only help when you reload the page.

**Comment by AlynxZhou** [comment]
I changed both view.js and notify.js, still not work, it loads once more but not scrolling down.

**Comment by lastzero** [comment]
It turned out that the way the back navigation was detected didn't work with the current browsers and Vue version anymore, so I introduced a new, more advanced detection method in our view helper. You are welcome to test it and provide feedback!

**Comment by AlynxZhou** [comment]
This times it works as intended. We could close this and I am waiting for the next stable release.

**Comment by AlynxZhou** [comment]
I am very appreciate for your work!
